### ISSUE TITLE
change test output files to BDD vocab

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#12]
E.g. HTML output could look like:-

```
Feature: BlogPosting (24 tests)
    Scenario: UserPostsToHisOwnBlog [01.01] Given a user named "Dr. Bill"
```

Note that we might consider removing example values from scenario descriptions and rely on the step description to include those values, e.g. "Given a user named \"{0}\"".Given(() => ...);

We'd need to consider whether to omit type arguments. It may be the case that type arguments are useful only unit testing, in which case it may be better to leave them included.

**Comment by jamesfoster** [comment]
I think this is a good move.

I was looking at removing the example values. It's relatively easy to remove them but because you now have several steps that have the same name and resharper sorts them you end up with:

```
TypeName.MethodName [01.01] Given
TypeName.MethodName [01.01] Given [2]
TypeName.MethodName [01.02] When
TypeName.MethodName [01.02] When [2]
```

So we need to add "example number" to the text. Something like `[Example.Context.Step]` but I couldn't see how to do this as InlineData attribute is handled by xunit and I couldn't see where that is captured by XBehave.

Also, In the resharper runner the type name and method name are already shown. It would be good to remove those to shorten the display names. It could even be optional. If there was an attribute you could apply at the assembly level with some formatting options people could choose which best suited them...

```
[assembly: XBehaveOptions(ShowParameters:false, ShowTypeName:false, ShowMethodName: false)]
```

Thoughts?

**Comment by adamralph** [comment]
I'd prefer to have a solution which worked for all runners, but if that's not possible then I think the assembly attribute is a good idea. `[Example]` is actually handled by xBehave and not xUnit. I had to override the behaviour so that `[Scenario]` could work both with and without a data attribute. I think the 'example number' approach could indeed work. It could perhaps be an extension to the numbering scheme which is already used, e.g. `[{isolation context].{step}]` could become `[{example}.{isolation context].{step}]`:

> TypeName.MethodName [01.01.01] Given
> TypeName.MethodName [01.01.02] When
> TypeName.MethodName [02.01.01] Given
> TypeName.MethodName [02.01.02] When

**Comment by jamesfoster** [comment]
In the pull request the [config properties](https://github.com/jamesfoster/xbehave.net/blob/2fb2afb549b2156a97210c472c80525ff4b904d4/src/Xbehave.Sdk.Net40/CurrentScenario.cs#L42) are static. These could be configurable however you see fit.

And I'm using the exact [formatting](https://github.com/jamesfoster/xbehave.net/blob/2fb2afb549b2156a97210c472c80525ff4b904d4/src/Xbehave.Sdk.Net40/ContextCommand.cs#L22) you've suggested `[01.02.03]`

**Comment by adamralph** [comment]
depends on #51

**Comment by adamralph** [comment]
This is solved by https://github.com/appccelerate/xBehaveMarkdownReport /cc @ursenzler
