### ISSUE TITLE
DateTime, DateTimeOffset, and Guid values in Examples

### ISSUE THREAD

**Issue by adamralph** [adamralph/xbehave.net#155]
``` C#
[Scenario]
[Example("2014-06-26")]
[Example("Mon, 15 Jun 2009 20:45:30 GMT")]
[Example("2009-06-15T13:45:30.0000000-07:00")]
public void Foo(DateTime bar)
{
```

``` C#
[Scenario]
[Example("2014-06-26")]
[Example("Mon, 15 Jun 2009 20:45:30 GMT")]
[Example("2009-06-15T13:45:30.0000000-07:00")]
public void Foo(DateTimeOffset bar)
{
```

``` C#
[Scenario]
[Example("{5B21E154-15EB-4B1E-BC30-127E8A41ECA1}")]
[Example("4EBCD32C-A2B8-4600-9E72-3873347E285C")]
[Example("39A3B4C85FEF43A988EB4BB4AC4D4103")]
public void Foo(Guid bar)
{
```

**Comment by adamralph** [comment]
Taken by @mat-mcloughlin.

**Comment by adamralph** [comment]
@mat-mcloughlin I thought I'd raise this so we have reference point for the work you're doing. Do you have something you can push up to your fork to show the locale problems you're having?

**Comment by mat-mcloughlin** [comment]
I'll have to push later as the changes are on the PC at home. However the problem is only with testing rather than functionality. 

I've been copying the way you've tested the rest of the arguments by using the `TestRunner.Run()` method and then checking the `DisplayName`. Now even though the code handles the correct locale this always seems to display in US date time format making it tricky to test

Thanks for the test cases btw, never thought to check a GUID without hyphens

**Comment by adamralph** [comment]
@mat-mcloughlin did you make any progress with this?

**Comment by mat-mcloughlin** [comment]
I totally forgot I'd started this.

Let me come back to you when I have a dig through my repos as I know I was close. Its just I'm a little busy starting a new job and all :)

**Comment by adamralph** [comment]
I've proposed this as [a feature in xunit](https://github.com/xunit/xunit/pull/1546). If accepted, xbehave will inherit the feature when it is linked to the next version of xunit.

**Comment by adamralph** [comment]
This [will be part of xunit 2.4.0](https://github.com/xunit/xunit/pull/1546#issuecomment-341987305), so the link to xunit 2.4.0 will provide this feature.
