### ISSUE TITLE
Render array elements in test output

### ISSUE THREAD

**Issue by ursenzler** [adamralph/xbehave.net#267]
When running these tests

```
    public class Foo
    {
        [Theory]
        [InlineData(new[] { "00:00-06:00" }, new[] { "05:45-10:00" }, new[] { "06:00-10:00" }, 4 * 60)]
        public void Theory(object[] a, object[] b, object[] c, int i)
        {    
        }

        [Scenario]
        [Example(new[] { "00:00-06:00" }, new[] { "05:45-10:00" }, new[] { "06:00-10:00" }, 4 * 60)]
        public void Scenario(object[] a, object[] b, object[] c, int i)
        {
        }
    }
```

the output looks like

![image](https://cloud.githubusercontent.com/assets/287565/9653835/87c3dbba-5226-11e5-9b3c-43a6b14dd99e.png)

Any idea, why the bare xunit test formats the arguments and the xbehave test doesn't?

**Comment by ursenzler** [comment]
btw, when replacing `Example` with `InlineData`, there is still no formatting when using xBehave.

**Comment by adamralph** [comment]
Interesting!

xbehave performs it's own rendering of the test names rather than using the rendering in xunit (due to supporting the generation of default values for method params). For the most part, `ToString()` is called on each argument but I guess xunit must be special casing arrays by calling `ToString()` for each element and rendering them in a square bracketed CSV. I'm sure we can just replicate this in xbehave easily enough.

**Comment by adamralph** [comment]
I guess we could also investigate what xunit does with other enumerable types and if there is any other special rendering we could also replicate it and expand the scope of this beyond just arrays.

**Comment by ursenzler** [comment]
@adamralph can you give me a pointer to where the rendering happens? I didn't find it :-(

**Comment by adamralph** [comment]
@ursenzler sure, here you go https://github.com/xbehave/xbehave.net/blob/30c9df9fe7f4736c54d68ef7e860facdf728e95e/src/Xbehave.2.Execution.desktop/ScenarioRunnerFactory.cs#L205

**Comment by ursenzler** [comment]
thanks. I'll try to integrate the xUnit magic into that method.

**Comment by adamralph** [comment]
Thank you!

**Comment by ursenzler** [comment]
@adamralph how can I create a nuget package from the xBehave sources/binaries. Is there something in the repo or do I have to create it myself?

**Comment by adamralph** [comment]
@ursenzler if you build it [using Rake](https://github.com/xbehave/xbehave.net/blob/dev/how_to_build.md) it will produce the nugets in `artifacts/bin/`.

**Comment by ursenzler** [comment]
@adamralph ah, okay.

**Comment by ursenzler** [comment]
sry to bother you again, but rake doesn't run successfully. It aborts with `NameError: uninitialized constant XUnitTestRunner`

**Comment by adamralph** [comment]
That usually means the wrong version of albacore is being used. Did you use bundler to install the gems and invoke rake?

**Comment by ursenzler** [comment]
I went through all the steps in the "how to build" again and I can build now. thanks. Had some gem updates.

**Comment by ursenzler** [comment]
Unfortunately, the `ArgumentFormatter` used in xUnit is internal.

My suggestion:
1. make a pull request to xUnit to make `ArgumentFormatter` public
2. for now, duplicate the code in xBehave.
3. once the `ArgumentFormatter` is public, use it and remove duplication.

What do you think?

**Comment by ursenzler** [comment]
Prototype working: 
![image](https://cloud.githubusercontent.com/assets/287565/9678083/aa2882e4-52e1-11e5-9c58-17633dfd6a5b.png)

**Comment by adamralph** [comment]
@ursenzler looks good!

I think your suggestion makes sense.

**Comment by adamralph** [comment]
So, it is indeed a little embarrassing that this hasn't been released yet. The reason was that 2.1 was always intended to be a release which added support for DNX/CoreCLR/dotnet/whatever-it's-called-this-month, in line with xunit 2.1, to keep the version numbers aligned. That work has been put [on hold](https://github.com/xbehave/xbehave.net/issues/224#issuecomment-213713639).

Given that the first xbehave release containing support for that nebulously named platform will be targeting some version of xunit > 2.1 (not to mention that keeping the xbehave and xunit minor version aligned for eternity probably isnt realistic anyway) I'm happy to push out 2.1 immediately, containing this feature. I'll do so ASAP.

/cc @ursenzler

**Comment by ursenzler** [comment]
woohoo!

**Comment by adamralph** [comment]
Thanks @ursenzler! Look out for your name in the release notes :trophy: 

https://www.nuget.org/packages/Xbehave/2.1.0
https://www.nuget.org/packages/Xbehave.Core/2.1.0
https://github.com/xbehave/xbehave.net/releases/tag/2.1.0
https://twitter.com/xbehavenet/status/725377198648098816
