### ISSUE TITLE
Adding .r(...) function as syntactic sugar to .OnFailure(RemainingSteps.Run)

### ISSUE THREAD

**Issue by iam3yal** [adamralph/xbehave.net#289]
Not sure if it makes sense but I've added it to my own project and it looks good. :)

**Comment by adamralph** [comment]
hi @eyalsk, thanks very much for the raising this.

I'm not sure that it makes sense to add this to the library. Ultimately, we could add one character shorthand synonyms for many parts of the API, but they would be rather cryptic to anyone not familiar with them, and if all libraries did this, we'd end up with code full of one character method calls. :wink:

I realise that xbehave is already somewhat guilty of this with `x()`. (And, unfortunately, its synonyms `f()` and `_()` which may well be deprecated at some point and eventually removed.) However, `x()` is not really shorthand for anything. It is a necessary evil for not being able to twist the language in a way that I'd really like for step definition. I.e. I don't really _want_ a method to exist between the step text and the step expression, but it's the only way to achieve this linkage in a nice, non-symbolic way in C#. In F#, for instance, we can do away with it altogether by [defining a custom operator](https://github.com/xbehave/xbehave.net-samples/blob/31184a388a8808dcb1bb6248baa5642ca3a4ebb7/src/Xbehave.Samples.FSharp.Net45.NCrunch/CustomOperator.fs#L23-L36). I guess `x()` could be interpreted as shorthand for a `Step()` or `Define()` method, but such longhand methods have never existed because of the verbosity they would introduce to a typical scenario.

I think the value of such shorthand synonyms is very much dependent on the user of the library. For instance, the running of subsequent steps on failure is something I've very rarely seen done so I've always considered it a rather edge case feature. If it's something you do very often, then the synonym will have a lot of value for you, but for most people it probably won't.

So, as much as I don't like turning down proposals, I'm leaning towards not doing this. As you say, you can provide it as an extension method in your own project, since it's something you use often and you find the shorthand convenient. I think that would be my general recommendation to anyone wanting some kind of shorthand synonym for this or any other part of the API.

I hope that sounds reasonable.

**Comment by iam3yal** [comment]
Yeah, I completely agree with you! thank you for elaborating! I was skeptical myself so it's fine haha.. :)

Keep up the good work! :)

**Comment by adamralph** [comment]
Thanks @eyalsk, I'll do my best! :smiley:
