### ISSUE TITLE
Watch values on Debug Session

### ISSUE THREAD

**Issue by Espartaco** [adamralph/xbehave.net#351]
Given the example, and assuming the test is more complex, but for example:

``` C#
public class CalculatorFeature
{
    [Scenario]
    public void Addition(int x, int y, Calculator calculator, int answer)
    {
        "Given the number 1"
            .x(() => x = 1);

        "And the number 2"
            .x(() => y = 2);

        "And a calculator"
            .x(() => calculator = new Calculator());

        "When I add the numbers together"
            .x(() => answer = calculator.Add(x, y));

        "Then the answer is 3"
            .x(() => Xunit.Assert.Equal(5, answer));
    }
}
```

When I debug the test in Visual Studio 2015 insert a breakpoint in line "...x(() => answer = calculator.Add(x, y));...."  and put mouse over X and Y  to see the values, always are zero (0), so I don't know real values and can't  analyze the problem.

**Comment by adamralph** [comment]
Hi @Espartaco, thanks for raising this.

My guess is that you have put your breakpoint on the entire statement, like so:

![image](https://cloud.githubusercontent.com/assets/677704/19700621/4e6432d6-9af8-11e6-9b2d-26d768db8477.png)

In order to debug a step, you must put the breakpoint on the expression body, like so:

![image](https://cloud.githubusercontent.com/assets/677704/19700637/64fa1a56-9af8-11e6-9828-ef28168027f1.png)

If you do this, you should see the values, as expected:

![image](https://cloud.githubusercontent.com/assets/677704/19700712/af353f92-9af8-11e6-8af7-e92a8581a008.png)

**Comment by adamralph** [comment]
@Espartaco I'm going to assume that my reply has solved your concern. Thanks again for raising this. If you need further help, please don't hesitate to ask again.
