### ISSUE TITLE
The Background feature

### ISSUE THREAD

**Issue by iam3yal** [adamralph/xbehave.net#409]
There are few minor issues with it.

1. The [example](https://github.com/xbehave/xbehave.net/wiki/Backgrounds) doesn't indicate that you can have a different method name other than `Background`.

2. The test runnner display the background test as inconclusive, I don't think it should really display it or is it a limitation? if so maybe it should be documented too.

3. The name of the steps shouldn't start with `(Background)` but maybe end with it, e.g., currently it looks like this `[01] (Background) Given a scanner` whereas I think it should read like this `[01] Given a scanner (Background)` so maybe it would be a good idea to add an option for it or just change it?

**Comment by adamralph** [comment]
@eyalsk thanks for raising this.

> 1. The [example](https://github.com/xbehave/xbehave.net/wiki/Backgrounds) doesn't indicate that you can have a different method name other than `Background`.

I've added a comment to explain this.

---

> 2. The test runnner display the background test as inconclusive, I don't think it should really display it or is it a limitation? if so maybe it should be documented too.

That should not be the case. The test should be marked as successful if it ran without problem. Which test runner are you using?

---

> 3. The name of the steps shouldn't start with `(Background)` but maybe end with it, e.g., currently it looks like this `[01] (Background) Given a scanner` whereas I think it should read like this `[01] Given a scanner (Background)` so maybe it would be a good idea to add an option for it or just change it?

It's a long time ago, but I think the reason I did that was to because tests might come out like this (borrowing from the [example in the Cucumber wiki](https://github.com/cucumber/cucumber/wiki/Background)):

```
MultipleSiteSupport.DrBillPostsToHisOwnBlog() [01] (Background) Given a global administrator named "Greg"
MultipleSiteSupport.DrBillPostsToHisOwnBlog() [01] (Background) And a blog named "Greg's anti-tax rants"
MultipleSiteSupport.DrBillPostsToHisOwnBlog() [01] (Background) And a customer named "Dr. Bill"
MultipleSiteSupport.DrBillPostsToHisOwnBlog() [01] (Background) And a blog named "Expensive Therapy" owned by "Dr. Bill"
MultipleSiteSupport.DrBillPostsToHisOwnBlog() [01] Given I am logged in as Dr. Bill
MultipleSiteSupport.DrBillPostsToHisOwnBlog() [01] When I try to post to "Expensive Therapy"
MultipleSiteSupport.DrBillPostsToHisOwnBlog() [01] Then I should see "Your article was published."
```

...and I thought that the background steps are much more distinct in that format than this:

```
MultipleSiteSupport.DrBillPostsToHisOwnBlog() [01] Given a global administrator named "Greg" (Background)
MultipleSiteSupport.DrBillPostsToHisOwnBlog() [01] And a blog named "Greg's anti-tax rants" (Background)
MultipleSiteSupport.DrBillPostsToHisOwnBlog() [01] And a customer named "Dr. Bill" (Background)
MultipleSiteSupport.DrBillPostsToHisOwnBlog() [01] And a blog named "Expensive Therapy" owned by "Dr. Bill" (Background)
MultipleSiteSupport.DrBillPostsToHisOwnBlog() [01] Given I am logged in as Dr. Bill
MultipleSiteSupport.DrBillPostsToHisOwnBlog() [01] When I try to post to "Expensive Therapy"
MultipleSiteSupport.DrBillPostsToHisOwnBlog() [01] Then I should see "Your article was published."
```

What do you think?

**Comment by iam3yal** [comment]
@adamralph 

> That should not be the case. The test should be marked as successful if it ran without problem. Which test runner are you using?

I'm using ReSharper.

> What do you think?

Well, I prefer the latter because I think that communicating that it runs as a `Background` should come second, the first question should be about what step ran before going into what kind of step it is.

Another reason and maybe THE reason, at least for me is when the window of the test runner in Visual Studio is docked vertically the name of the test becomes more important than any other information.

**Comment by adamralph** [comment]
@eyalsk I managed to reproduce the problem you mentioned regarding the background showing as an inconclusive test:

![image](https://user-images.githubusercontent.com/677704/33805285-8117cca4-ddb6-11e7-84d2-ff1862786fce.png)

The test which is marked as inconclusive is actually a dummy test. ReSharper discovers that the method is marked with `[Background]` (which derives from xunit's `[Fact]`) so it shows it as a test in the test explorer. However, because this method is only a background and not an actual scenario, it doesn't yield any tests (steps) itself. The background steps which it defines are discovered when the scenario is discovered and they are shown as part of the scenario (see red arrows). As you can see those steps are correctly marked as successful. I guess the reason that I hadn't noticed this before is that I don't use ReSharper, and other test runners ignore the background methods completely because they do not yield any tests.  I'm not sure why ReSharper believes it's a good idea to show them and mark them as inconclusive. @citizenmatt, do you have comment on that?

**However**, I also realised, during this investigation, that xBehave's `[Background]` does not need to inherit from xunit's `[Fact]`. The inheritance is completely redundant. I think I added the inheritance while I was building xbehave 2.0, thinking it would be required, but then failed to realise that it was redundant when I implemented background steps. I'll [remove the inheritance in xbehave 2.3.1](https://github.com/xbehave/xbehave.net/issues/410), which means that this dummy inconclusive test will disappear, even if no changes are made to ReSharper.

---

Regarding the changing format of the background step names, I'll also [add something to 2.3.1 to allow this](https://github.com/xbehave/xbehave.net/issues/411).

**Comment by iam3yal** [comment]
@adamralph These changes will make me so happy! Thank you! ❤️

**Comment by adamralph** [comment]
You're welcome @eyalsk. 😄 

I'm closing this issue now, since the three points have been addressed (or will be in separate issues). Thanks again for raising this.

**Comment by citizenmatt** [comment]
I think ReSharper is behaving as expected here - the `[Background]` method is marked as a test, so it's being shown as a test, and it's giving a warning that it wasn't run.

If it's not actual a test, then removing the `FactAttribute` base sounds like a good move to me.

**Comment by adamralph** [comment]
@citizenmatt I'm going to remove it anyway, but note that other test runners, e.g. the VS runner, or TestDriven.NET, do not show this test method at all. I guess they completely ignore any test method which does not yield any tests at either discovery or run time.

**Comment by citizenmatt** [comment]
Well, yeah, they're different products with different aims. They're only showing the tests that are currently running or have been run. They get completely accurate test lists, but the trade off is that they're historical snapshots. They will show obsolete tests when you edit the file, and don't show new tests as you add them.

ReSharper has a different approach, and tries to show a test list of _what it expects to run_, as well as what is currently running, or just been run. It tries to show a current list of tests at all times. It does this by performing discovery at edit time, looking at source code, rather than just at compile time. This gives us a lot of goodness - namely user interaction with tests before you've compiled. Invoke run, debug or profiling on a brand new test, straight from the editor without compiling. 

But the trade off is that we don't have as much information at edit time as we do at compile time. And in this case, it means that we show a test that we expect to run, but doesn't produce any tests. I think it would go against the principle of least surprise to show a test as expected to run, and then not show what happened to it.

**Comment by adamralph** [comment]
@citizenmatt thanks for the explanation. That all makes sense, and it's a good future reference point.
