### ISSUE TITLE
Depend on xunit.core rather than xunit

### ISSUE THREAD

**Issue by ma499** [adamralph/xbehave.net#426]
The Nuget packaging creates a dependency between XBehave and the "xunit" meta package. I would prefer if the dependency was instead on xunit.core (and directly on any other xunit libraries that are required). That way I do not, for example, need to build my project with xunit.assert (included by the xunit metapackage) when I'm using an alternative assertions library, such as Fluent Assertions.

**Comment by adamralph** [comment]
@ma499 thanks for raising this.

The [Xbehave.Core](https://www.nuget.org/packages/Xbehave.Core) package is designed exactly for this purpose. It depends on `xunit.core` instead of `xunit`. Can you please give it a try to see if it solves your requirement?

I'll add a page to the FAQ about this shortly.

**Comment by adamralph** [comment]
FAQ added: https://github.com/xbehave/xbehave.net/wiki/Can-I-use-xBehave.net-without-introducing-xunit.assert%2C-xunit.analyzers%2C-etc.%3F

**Comment by ma499** [comment]
Ah, works fine. Thank you!

**Comment by adamralph** [comment]
You're welcome. 😃
