### ISSUE TITLE
Support for xunit 2.2.x

### ISSUE THREAD

**Issue by jotatoledo** [adamralph/xbehave.net#434]
**Current behavior**

According to https://github.com/xbehave/xbehave.net/issues/374, the avaialble versions of xbehave arent compatible with xunit 2.2.x. There might be devs out there who have a dependency on xunit@2.2.x, and because of this, they cant use this lib.

**Expected behavior**

Support xunit 2.2.x

**Comment by adamralph** [comment]
@jotatoledo FYI I'm still looking into this, but it turns out to be non-trivial, since xunit switched from PCL to .NET Standard in 2.2. The 2.1 xbehave tag is still using the old csproj, so that means dumping that and creating a new csproj based on the new SDK format, and then upgrading to xunit 2.2, plus all the work to retarget the resulting NuGet package. I'm not saying it won't happen, but it may take a bit longer until I get to it (any help appreciated 😉).

Out of interest, what is the test runner that you mentioned you are using, that is stuck on xunit 2.2? Is there any possibility of getting it upgraded to xunit 2.3?

**Comment by jotatoledo** [comment]
Thanks for the update. I would gladly contribute in any way that I could, but I most likely lack the knowledge related to the .net standard. Because of this I cant promise any help on the short term.

The runner is called AxoCover. There is an open issue on its tracker already https://github.com/axodox/AxoCover/issues/129

**Comment by adamralph** [comment]
@jotatoledo I spent some time on this today, but it soon got too complicated to be worth pursuing. While I'd like to have an xbehave 2.2 for completeness (so there's a matching xbehave for every xunit minor), the return on investment in ticking the 2.2 box is not really worth it. It could take me days to get this working. I believe it's better to push for AxoCover to support xunit 2.3, which has been around for over 6 months already.

Note that although I missed getting an xbehave 2.2 released for xunit 2.2, it is my intention to have a matching xbehave version for every xunit version from now on.
