### ISSUE TITLE
Rerun tests in TFS

### ISSUE THREAD

**Issue by emi662002** [adamralph/xbehave.net#519]
Hi,

When running Scenarios each step is seen by TFS as a single test. Having a scenario with 10 steps, is seen then as 10 individual tests.

I have for example these 2 steps, and in TFS these are shown as individual tests passing or not:

```
018-11-06T02:12:47.3462465Z Passed
    AssignmentsApi.Tests.Integration.AssignmentQuestionsFeature.AnsweringAssignmentQuestions()
    [09] And the questions are answered
```

```
2018-11-06T02:13:35.1744479Z ##[error][xUnit.net 00:01:49.5166222]
    AssignmentsApi.Tests.Integration.AssignmentQuestionsFeature.AnsweringAssignmentQuestions()
    [10] (Teardown) [FAIL]
```

The problem is when I activate the option  "Rerun failed tests" (TFS 2018) which will retry the failed tests. As you can expect, TFS retries only the failing step. That is the main part of the issue. It won't retry the scenario but the individual scenario step.

The side effect part of the issue is that when retrying I see the exception:

```
##[error]Incorrect format for TestCaseFilter
    Error: Empty parenthesis ( ). Specify the correct format and try again.
    Note that the incorrect format can lead to no test getting executed.
```

becase the retry is done using the step name, instead of the scenario name

```
No test matches the given testcase filter
     `FullyQualifiedName=MOO.Backend.AssignmentsApi.Tests.Integration.AssignmentQuestionsFeature.MOO.Backend.AssignmentsApi.Tests.Integration.AssignmentQuestionsFeature.AnsweringAssignmentQuestions()
    [10] (Teardown)
```

**Comment by adamralph** [comment]
Hi @emi662002, thanks for raising this. I'll form an answer and get back to you ASAP.

**Comment by adamralph** [comment]
@emi662002 sorry for the delay. This sounds like a TFS problem. Before I explain why, I need to provide some background information:

xunit is built around the concepts of "test cases" and "tests". If you use a local test runner with a GUI, what you see in the GUI are _test cases_. When you run a test case, that usually results in the running of a single _test_. However, in some cases, running a single test case may result in the running of _more than one test_.

One example is an xunit theory which has input data which cannot be serialised. Test cases are found at _discovery time_. This is when the test runner examines the test library and _discovers_ the test cases. At this point, if the input data for the theory is serialisable, the test runner can record it, and present a separate test case in the GUI for each set of input data found. When you run that test case from the GUI, the serialized input data found at discovery time is passed to the theory method, resulting in a single test being run. However, if the input data found at discovery time is _not_ serialisable, the test runner cannot store it, so it cannot present a separate test case for each set of input data, since it would not be able to pass the input data to the theory method at runtime. The best it can do is to present a single test case for the entire theory. When you run that test case from the GUI, the input data is retrieved from its source and passed directly to the theory method, once for each set of input data. That means multiple tests are run for the single test case you invoked.

Another example of multiple tests per test case is an xbehave scenario. At discovery time, the scenario methods are found, and the test runner presents each of them as a test case. When you execute the test case for a given scenario from the GUI, the scenario method is invoked, and a test is run for each step in the scenario, again resulting in multiple tests for the single test case.

So what this means is that after discovery, only the test cases found can be shown in a test runner GUI. After running the test cases, the GUI can also show the actual tests that were run. Sometimes that's one per test case, sometimes it's more. Importantly, the test cases and the tests are _two different things_. Test cases are things that the test runner knows how to run. Tests are just a representation of what happens when you run a test case.

Now, a well behaved test runner GUI knows that after running test cases, it should only allow re-running of _those same test cases_. It makes no sense to allow the running of the _tests_, since the test runner cannot guarantee that it knows how to invoke them. For example, in the case of an individual test that resulted from running an xunit theory with non-serialisable input data, it doesn't know what data that test was invoked with, so how can it know how to re-run that specific test? In the case of an xbehave scenario, the individual tests do not even correspond to methods, so how can the test runner know how to re-run that specific test? The errors you are seeing reflect that.

The conclusion I draw from this is that TFS is not respecting the difference between test cases and tests. Because this is usually a one to one relationship, it is making a false assumption that a test which was run at run time is also one that can be invoked as if it were found at discovery time.

I recommend searching to see if anyone has reported a similar issue in TFS with xunit theories with input data that is not serialisable. If my diagnosis is correct, then both xbehave and xunit are behaving correctly, and this is essentially a problem with TFS not respecting the xunit abstractions. If that's the case then there is nothing that can be done in either xunit or xbehave to fix this problem. It will have to be fixed in TFS.

@bradwilson do you agree with my diagnosis?

**Comment by bradwilson** [comment]
Seems reasonable.

**Comment by emi662002** [comment]
Wow! I expected the outcome, but I really appreciate the amazing answer, thanks for taking the time! I will go further on the TFS side of the story.

**Comment by adamralph** [comment]
@emi662002 if you've raised a public issue with TFS, would you mind posting a link here? It would be useful for anyone else having the same problem to track it. I may also add an FAQ about this.

**Comment by emi662002** [comment]
Sure, I will post the link as soon as I have one. There's some info also
telling that this will be fixed on TFS 2019....

**Comment by emi662002** [comment]
I didn't raise an issue because i found the following:

https://github.com/Microsoft/azure-pipelines-tasks/issues/6294#issuecomment-362151476


https://github.com/Microsoft/azure-pipelines-tasks/issues/7037#issuecomment-387053113 be aware with this one; batching is not the solution, it gives false positives.

**Comment by adamralph** [comment]
Thanks for the links @emi662002. I have to admit I find those issues difficult to understand. It's not clear to me whether resolving either of them will fix this problem.

I get the impression that running tests within test cases in TFS currently suffers from many issues. I guess the first thing they need to fix is the more common case where tests within test cases are known at discovery time (e.g. xunit theories with serialisable data). The rarer case is tests within test cases that are only known at runtime (e.g. xunit theories with non-serialisable data/xbehave scenarios). I hope when they fix the common case, it will be obvious to them that they should not allow the running of specific tests in the rarer case, but my confidence isn't high.

I wonder if it's still worth raising an issue to describe this specific problem explicitly. I would happily do that, but I've never used (or even seen) TFS so I'm not sure I could describe it in meaningful terms from the outset. I'd be more than happy to chime in and explain the problem with respect to xunit abstractions.
