### ISSUE TITLE
Support for Excel based iterations as test data

### ISSUE THREAD

**Issue by tmpalaniselvam** [adamralph/xbehave.net#546]
Hi Team,
 I'm looking for excel based data driven support from BDD tools. Do you provide the feature to utilize the excel data as parameterization?

Thanks,
Palani

**Comment by adamralph** [comment]
Hi @tmpalaniselvam, thanks for asking this question.

An xBehave.net scenario will use data provided by any attribute which derives from [`Xunit.Sdk.DataAttribute`](https://github.com/xunit/xunit/blob/d321bb572abf9027e3762848068b3e9eea2458f2/src/xunit.core/Sdk/DataAttribute.cs). That includes the attributes built in to xunit - `ClassDataAttribute`, `InlineDataAttribute`, and `MemberDataAttribute` - and any custom attributes. This is documented in the [wiki](https://github.com/xbehave/xbehave.net/wiki/Scenarios-with-examples). xBehave.net itself does not provide any further data attributes.

xUnit.net 1.x had an `ExcelData` attribute, but it was removed in xunit 2.0. At one time there was a sample for xUnit.net 2.0 but it was [removed](https://github.com/xunit/samples.xunit/commit/60d42e01b5edaa98877a10274d9469588d277dbb).

You may be able write your own attribute which retreives data from Excel, or perhaps there is a third party package somewhere which provides one. There is also an [example showing how to provide data from a CSV file](https://stackoverflow.com/a/45885539/49241). Perhaps that would work for you instead of an Excel file? Or at least it may give you an idea of how to write an attribute which works for Excel files.

**Comment by tmpalaniselvam** [comment]
Hi @adamralph ,

Thanks for the detailed reply. I will try this.
