### ISSUE TITLE
Q: What's the difference between LiteGuard.Source and Validation

### ISSUE THREAD

**Issue by mwpowellhtx** [adamralph/xbehave.net#665]
[`Validation`](https://www.nuget.org/packages/Validation), or [`Validate.Fluently`](https://www.nuget.org/packages/Validate.Fluently), which builds on `Validation` except in a fluent manner.

Experimenting with a couple of things, when I replace the *Guards* as such, tests start to fail, at minimum. But when `LiteGuard.Source` is in the loop, things work fine.

Curious... Thanks!

**Comment by mwpowellhtx** [comment]
For giggles, I threw in a *QnD* unit test around either path. Which all told I don't think the issue, why *LiteGuard* "works" and *Validations* do not, is the code itself.

```C#
object obj = null;

Action requiresAction = () => Requires.NotNull(obj, nameof(obj));

Action guardAction = () => Guard.AgainstNullArgument(nameof(obj), obj);

var guardEx = Assert.Throws<ArgumentNullException>(guardAction);

var requiresEx = Assert.Throws<ArgumentNullException>(requiresAction);
```

**Comment by adamralph** [comment]
@mwpowellhtx I'm afraid I'm not familiar with `Validation` or `Validate.Fluently`.

**Comment by mwpowellhtx** [comment]
@adamralph Okay, I appreciate that. I'm not sure what the difference is, other than it seems *LiteGuard.Source* appears to drop some actual code in the build.

Is it the worst thing ever if a validation package reference traveled with a BDD, or any other, TDD, package, i.e. whether internally as `PrivateAssets="all"`?

I'll close it out here. Appreciate your insights on that subject.

Thank you...

**Comment by adamralph** [comment]
> Is it the worst thing ever if a validation package reference traveled with a BDD, or any other, TDD, package, i.e. whether internally as `PrivateAssets="all"`?

Sorry, I don't understand what you are asking here.

**Comment by mwpowellhtx** [comment]
@adamralph In the current rendition of the BDD package, *LiteSource.Guard* literally injects code into the build stream correct?

Contrast that with a full package reference, i.e. not `PrivateAssets="all"`, that travels with the package.

Just curious, would that be the worst thing ever? Is there reasoning why not to do that?

Or perhaps could be done in a `Configuration=Debug` only?

Thanks...

**Comment by adamralph** [comment]
> In the current rendition of the BDD package, _LiteSource.Guard_ literally injects code into the build stream correct?

Correct. `LiteGuard.Source` is a source code package. These are fairly common.

> Contrast that with a full package reference, i.e. not `PrivateAssets="all"`, that travels with the package.
> 
> Just curious, would that be the worst thing ever? Is there reasoning why not to do that?
> 
> Or perhaps could be done in a `Configuration=Debug` only?

What are the proposed benefits of changing it?

**Comment by mwpowellhtx** [comment]
Oh, I'm not proposing you change it here. I'm just trying to wrap my head around it as an architectural decision.

Are there any benefits, for instance, extending guards into the runtime, consumer side of things, for instance?

In debug, sure, I could see that.

**Comment by adamralph** [comment]
Well, every dependency has a cost. A package with no dependencies is easier to maintain and consume. By using `LiteGuard.Source`, instead of `LiteGuard`, the code is compiled into the xbehave package, so it doesn't need to take a package dependency.

**Comment by mwpowellhtx** [comment]
Yes, but does it provide any value to the end consumer? Or is it really just a safety net during the debugging, unit testing process?

**Comment by adamralph** [comment]
@mwpowellhtx that's difficult to quantify. It's really just defensive programming in the absence of a language feature: non-nullable reference types._*_

If an argument is null and is de-referenced, without the guard clauses, an obscure `NullReferenceException` is thrown with, at most, a line number. With the guard clauses, a more meaningful exception is thrown and the problem is easier to trace. Having said that, if each of the guard clauses is inspected to find the origin of the protected arguments, it's probably usually somewhere in xunit. If, in turn, the xunit source is inspected, it may be found that the arguments cannot be null. In that case, the guard clauses are redundant and can be removed. That would however, assume that future versions of xunit will not change so that a null argument can be passed, but that would probably be indicative of a bug in xunit. Perhaps the guard clauses are a little over-defensive, but they're not causing much noise for now. Maybe in a future version of xbehave we may decide to dispose of them.

_\* C# 8.0 has this. It's confusingly (to me at least) named ["Nullable reference types"](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references). If this becomes ubquitous then LiteGuard, in all it's forms, will become redundant. This is [acknowledged](https://github.com/adamralph/liteguard/blob/master/README.md) in the LiteGuard README._

**Comment by mwpowellhtx** [comment]
@adamralph Don't get me started on the utility of NRTs. I understand what they are, and quite frankly I think that `C#` as a language was perfectly capable, more so today with the advent of operators such as `??=` of reasoning by devs and their teams over the `null` "issue."

Again, not proposing to drop the guards altogether. I'm experimenting with them and I wonder whether they could possible be useful in `Debug`, but factored out for a `Release`, is all.

Anyway, thank you for the discussion, and Happy 4th 🎆 !

**Comment by adamralph** [comment]
@mwpowellhtx I think if I were to remove them, I'd remove them completely. I don't see any value in having them for `Debug` only.

**Comment by adamralph** [comment]
@mwpowellhtx I think if I were to remove them, I'd remove them completely. I don't see any value in having them for `Debug` only.
