### ISSUE TITLE
[Gitter] OAuth issue

### ISSUE THREAD

**Issue by mwpowellhtx** [adamralph/xbehave.net#738]
Why ever does the *xBehave.net* *gitter* need access to things like 

```
repo
user:email
read:org
```

What business is it of *gittter* or *xBehave.net* `repo` or `read:org`, in particular, *Public and private repositories*, *Organizations and teams*, or any of it for that matter?

**Comment by adamralph** [comment]
Hi @mwpowellhtx, Gitter is an external service which I have no control over. I have no idea why it requests the permissions that it does. You'll have to take this up with Gitter.

**Comment by thomaslevesque** [comment]
@adamralph does the Gitter room for xBehave.net even exist?
My guess is that @mwpowellhtx tried to find the Gitter room by entering the URL, saw the following message because the room doesn't exist, and clicked "Click here to do this now", which showed the consent screen for [Github Private Repo access](https://gitlab.com/gitterHQ/webapp/blob/develop/docs/oauth-scopes.md#github).

![image](https://user-images.githubusercontent.com/1864281/101292826-22d6c780-3812-11eb-99c2-e436c4c305b7.png)

**Comment by adamralph** [comment]
> does the Gitter room for xBehave.net even exist?

I have no idea.

I guess that people may have been finding it since http://xbehave.github.io/ had a link to it. I've just pushed a commit to make that site into a redirect back to this repo.

**Comment by mwpowellhtx** [comment]
Pretty certain the channel did exist before, not sure if it was yours or someone else's to be honest. I am subscribed to dozens of others and do not have the same issue, but if it is not your channel, then disregard I suppose.
